name: housingiq
version: '1.0.0'
config-version: 2

profile: housingiq

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  housingiq:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics
      +contract:
        enforced: true

vars:
  # Default date for incremental loads
  start_date: '2000-01-01'
